env: "local" # local, dev, prod
storage_path: "./storage/storage.db"
alias_length: 6
http_server:
  address: "localhost:8082"
  timeout: 4s # время на чтение запроса / отправку ответа
  idle_timeout: 60s # время жизни соединения с клиентом
